version: "3"

services:
  web:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./www:/srv/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www
    depends_on:
      - phpfpm
          
  phpfpm:
    image: markoshust/php:fpm-alpine
    volumes:
      - ./www:/srv/www
    networks:
      - www
    env_file: .env
    depends_on:
      - mysql

  mysql:
    image: percona
    ports:
      - 33061:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - www
    env_file: .env

volumes:
  dbdata:

networks:
  www:
